server.port=${PORT:8080}

spring.config.import=optional:file:.env[.properties],optional:file:./www/calculator/.env[.properties],optional:file:/www/calculator/.env[.properties]
api.key=${API_KEY:}

spring.main.lazy-initialization=true
spring.main.banner-mode=off
logging.level.root=ERROR